### ISSUE TITLE
能够提供为程序发送的消息自动添加标记（小尾巴或 Tag）的功能吗？

### ISSUE THREAD

**Issue by Initial-heart-1** [MistEO/FileQQ#1]
如果我使用的账号同时有运行 bot，那么这将有助于辨别消息来源

**Comment by MistEO** [comment]
你还真用啊.jpg

**Comment by Initial-heart-1** [comment]
用，必须用
你做不做吧.mp3
为什么不交 PR？卷不过玛丽啊 QAQ

**Comment by Initial-heart-1** [comment]
omg 真的有人做了

**Comment by bakashigure** [comment]
> omg 真的有人做了

vscode-qq 我彻底登不上了, 被迫使用玛丽的 fileqq(

**Comment by Initial-heart-1** [comment]
有什么区别吗（

**Comment by bakashigure** [comment]
> 有什么区别吗（

vscode-qq 太久没更新了, 所有的协议都无法登录了，也没办法使用watch协议扫码
